import fs from "fs";
import path from "path";
import { transformSync } from "esbuild";

type ConvertFileConfig = {
  sourcePath: string;
  targetPath: string;
};

const fileList: ConvertFileConfig[] = [
  {
    sourcePath: path.resolve("src/jswasm/sqlite3-opfs-async-proxy.js"),
    targetPath: path.resolve("src/jswasm/opfs-proxy-asset.js"),
  },
];

for (const { sourcePath, targetPath } of fileList) {
  try {
    const sourceCode = fs.readFileSync(sourcePath, "utf-8");

    // Minify the proxy script using esbuild
    const result = transformSync(sourceCode, {
      minify: true,
      format: "iife",
    });

    // Generate the asset file with the minified string export
    const output = `// Generated by scripts/bundle-proxy-asset.ts - DO NOT EDIT\nexport const opfsProxyContent = ${JSON.stringify(
      result.code,
    )};\n`;

    fs.writeFileSync(targetPath, output);
    console.log("✅ Successfully bundled minified OPFS proxy asset.");
  } catch (err) {
    console.error("Error bundling OPFS proxy asset:", err);
    process.exit(1);
  }
}
